---
# Playbook to create local user and add to groups

- hosts: windows

  tasks:
    - name: create user
      win_user:
        name: Username
        password: "P@55w0rd"
        password_never_expires: true
        account_disabled: no
        account_locked: no
        password_expired: no
        state: present
        groups:
          - Администраторы
